### ISSUE TITLE
Validation Error: Missing City / State

### ISSUE THREAD

**Issue by jayyovs** [zschumacher/setlist-fm-client#2]
A validation error manifests when a venue does not have a City or State populated ([example](https://www.setlist.fm/setlist/grateful-dead/1978/the-pyramids-giza-egypt-bd605b6.html))

`ValidationError: 2 validation errors for ArtistSetListResponse
setlist -> 9 -> venue -> city -> state
  field required (type=value_error.missing)
setlist -> 10 -> venue -> city -> state
  field required (type=value_error.missing)`

**Comment by zschumacher** [comment]
this is fixed in version 0.4.0!
